### ISSUE TITLE
304 errors when playing video (also images) in RiseCache-Test.jar (Ubuntu 14.04/15.10)

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-cache#5]
**How to Duplicate**
1. Chr ver 47
2. No RiseCache-Test.jar
3. Clear all rise cache before and after running each Presentation.
4. Use Video Folder schedule and presentation http://rva.risevision.com/#/SCHEDULE_MANAGE/id=2f4ae1be-1dbd-4e94-aa5a-581b95379a97?cid=960b72df-9af7-476b-8a47-b67ded4c779d
5. Then use Video schedule and presentation http://rva.risevision.com/#/SCHEDULE_MANAGE/id=1afe3fd2-4c70-4d9e-aa15-4acf650f32a8?cid=960b72df-9af7-476b-8a47-b67ded4c779d (includes external and Storage)

When the players are on the supplied Chr 47 and new RiseCache-Test.jar either:
1. All videos download into cache but not all videos play.
2. Not all videos download into cache and not all videos play.

In the RiseCache.log I am seeing:
“Download cancelled.  Response code 304 received for URL…" 
The download cancelled could be any of the video material so it’s not specific to a type of video.

This happens several times on 14.04 and 15.10 32/64bit Ubuntu for Video and Video Folder.
Also I’ve noticed that once this happens, the video does not ever play having run the presentation extended (i.e. 30min)

When the players are on the supplied Chr 47 and not on the new RiseCache-Test.jar
1. All videos download into cache and all videos play.

**Images**
I've also noticed this happening across for the Image Folder Widget.  Can send through logs and do another test run for Image Folder.

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qi3Dtpvu&#x2F;868-issue-5-rise-cache"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue 5 Rise Cache</a>

**Comment by tejohnso** [comment]
@hcs0 Is this happening with current rise cache?  If not, please close.

**Comment by hcs0** [comment]
@tejohnso No issue observed in the current Rise Cache cc @rodrigopavezi
