### ISSUE TITLE
Rise Cache: 404 Not Found/Server Response: Forbidden [Images]

### ISSUE THREAD

**Issue by ashleighalmeida** [Rise-Vision/rise-cache#9]
How it works now:

User launches presentation in Rise Player with a "Problem retrieving images from cache" error that is shown where the images should load.

Console:

![image](https://cloud.githubusercontent.com/assets/11686685/12402692/9d0bb65e-bdfc-11e5-96e5-81533d402c5c.png)

Cache: Response 403

Images are not getting downloaded to the cache, despite the fact that they are accessible via browser/CAP.

How it should work:

User should be able to view their images in their presentation using Rise Player.

http://rva.risevision.com/#/SCHEDULE_MANAGE/id=4f1faf33-f114-49ff-b2b4-845d70058caa?cid=998502d9-ffbf-4150-8d64-c217d20378eb

**Comment by ashleighalmeida** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/apa@risevision.com/conversations/1747472256

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;t7d6k00O&#x2F;867-github-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> GitHub Issues</a>

**Comment by tejohnso** [comment]
@rodrigopavezi Is this the SSL issue that we've already discussed?

**Comment by rodrigopavezi** [comment]
@tejohnso I think this is fixed with the add of the User-Agent. 
@ashleighalmeida could you confirm this issue is not happening anymore with the latest RiseCache? cheers

**Comment by hcs0** [comment]
@rodrigopavezi I was testing the presentation that @ashleighalmeida was working on (Uni of St Francis) and can confirm that this is no longer an issue.  I will close this.

**Comment by rodrigopavezi** [comment]
@hcs0 thanks!!!

**Comment by tejohnso** [comment]
:+1:
